version: '2'
services:
    apache.local:
        build:
            context: ./apache
        container_name: jiboule-apache
        hostname: apache
        domainname: local
        tty: true
        volumes:
            - /var/www:/var/www
        ports:
            - 80:80
        expose:
            - 80

    jiboule-node:
        build: node
        container_name: jiboule-node
        hostname: node
        domainname: jiboule.dev
        tty: true
        restart: always
        volumes:
              - /var/www:/var/www
        ports:
              - 8070:8070
              - 9966:9966
