jiboule-node:
  build: node
  container_name: jiboule-node
  hostname: node
  domainname: jiboule.dev
  tty: true
  restart: always
  volumes:
        - /var/www:/var/www
  ports:
        - 8070:8070
        - 9966:9966
